Fixes requirements problems that prevent running
When trying to run the service, one gets an error:
     from werkzeug import FileStorage
 ImportError: cannot import name 'FileStorage'

which is remedied by a requirements upgrade
(https://stackoverflow.com/a/60211005/1789582)